const fieldSynonyms = {
  fname: [
    "firstName",
    "first_name",
    "fname",
    "givenName",
    "given_name",
    "first",
  ],
  mname: [
    "middleName",
    "middle_name",
    "mname",
    "m_initial",
    "midName",
    "middle",
  ],
  lname: [
    "lastName",
    "last_name",
    "lname",
    "surname",
    "familyName",
    "family_name",
    "last",
  ],
  preferredName: [
    "preferredName",
    "nickname",
    "display_name",
    "alias",
    "second_name",
    "preferred_name",
  ],
  dob: [
    "dob",
    "birthDate",
    "birth_date",
    "dateOfBirth",
    "date_of_birth",
    "birthday",
    "participant_birthday",
    "child_dob",
    "birthday",
    "birth",
    "date",
  ],
  gender: [
    "gender",
    "sex",
    "gender_identity",
    "participant_gender",
    "child_gender",
    "user_gender",
    "user_sex",
    "child_sex",
    "participant_sex",
  ],
  nationality: [
    "nationality",
    "citizenship",
    "country_of_origin",
    "visa_status",
    "origin",
    "birth_place",
    "country_of_birth",
  ],
  email: ["email", "emailaddress", "useremail", "emailid", "email_id"],
  phone: [
    "homephone",
    "phone",
    "phonenumber",
    "contactnumber",
    "mobile",
    "cell",
    "number",
    "workphone",
    "personalphone",
  ],

  address: [
    "address",
    "street",
    "street_address",
    "residence_address",
    "residence",
    "home",
    "home_address",
  ],
  city: ["city", "town", "municipality"],
  state: ["state", "province", "region"],
  zip: ["zip", "postalCode", "postal_code", "zipcode", "zip_code", "code"],
  country: ["country", "nation", "country_name", "counteryName"],

  username: ["username", "user", "login", "user_id", "userid"],
  password: ["password", "pass", "pwd", "passcode", "secret"],

  ccNumber: ["cc-number", "credit_card_number", "card_number", "ccn"],
  ccExpiry: ["cc-expiry", "credit_card_expiry", "expiration_date", "exp_date"],
  ccCvv: ["cc-cvv", "cvv", "card_cvv", "security_code"],

  notes: [
    "notes",
    "comments",
    "remarks",
    "additional_info",
    "additional_notes",
    "sidenotes",
    "additional_comments",
  ],
};
